<?php
/**
 * @file
 */

function crm_student_init() {
  drupal_add_css(drupal_get_path('module', 'crm_student') .'/css/crm_student.css');
}

/**
*	Implementation of hook_form_FORM_ID_alter
*	Here we're changing how the search box works
*/
function crm_student_form_views_exposed_form_alter(&$form, $form_state) {
	$form['submit']['#attributes']['class'][] = 'element-invisible';
	$form['contact_name_value']['#attributes']['class'][] = 'search-box';
	$form['contact_name_value']['#attributes']['placeholder'] = t('Search');
	$form['#info']['filter-contact_name_value']['label'] = '<span class="element-invisible">' . $form['#info']['filter-contact_name_value']['label'] .'</span>';
}
