<?php

function crm_relation_link_menu() {
	$items = array();
	
	$items['relation/create/%/%/%/%/%'] = array(
		'title' => 'Create relation',
		'page callback' => 'crm_relation_link_manage',
		'page arguments' => array(1, 2, 3, 4, 5, 6),
		'access arguments' => array('create relations'),
	);
	
	$items['relation/delete/%/%/%/%/%'] = array(
		'title' => 'Delete relation',
		'page callback' => 'crm_relation_link_manage',
		'page arguments' => array(1, 2, 3, 4, 5, 6),
		'access arguments' => array('delete relations'),
	);
	
	return $items;
}

function crm_relation_link_manage($action, $relation_type, $source_id, $source_type, $target_id, $target_type) {
	if($action == 'create') {
		if($relation = relation_create($relation_type, )) {
			relation_save($relation);
		}
	}
}