<?php

/**
 * @file
 * Module for the crm_note Entity - a starting point to create your own Entity
 * and associated administration interface
 */  


/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function crm_note_entity_info() {
  $return['crm_note'] = array(
    'label' => t('crm_note'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'crm_note',
    'controller class' => 'crm_noteController',
    'base table' => 'crm_note',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'crm_note_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the crm_note types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'crm_note_create',
    'access callback' => 'crm_note_access',
    'module' => 'crm_note',
    // The information below is used by the crm_noteUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/crm_notes',
      'file' => 'crm_note.admin.inc',
      'controller class' => 'crm_noteUIController',
      'menu wildcard' => '%crm_note',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['crm_note_type'] = array(
    'label' => t('crm_note Type'),
    'entity class' => 'crm_noteType',
    'controller class' => 'crm_noteTypeController',
    'base table' => 'crm_note_type',
    'fieldable' => FALSE,
    'bundle of' => 'crm_note',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'crm_note_type_access',
    'module' => 'crm_note',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/crm_note_types',
      'file' => 'crm_note_type.admin.inc',
      'controller class' => 'crm_noteTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the crm_note types via a hook to avoid a recursion
 * issue as loading the crm_note types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function crm_note_entity_info_alter(&$entity_info) {
  foreach (crm_note_get_types() as $type => $info) {
    $entity_info['crm_note']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/crm_note_types/manage/%crm_note_type',
        'real path' => 'admin/structure/crm_note_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer crm_note types'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function crm_note_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer crm_note types' => array(
      'title' => t('Administer crm_note types'),
      'description' => t('Create and delete fields for crm_note types, and set their permissions.'),
    ),
    'administer crm_notes' => array(
      'title' => t('Administer crm_notes'),
      'description' => t('Edit and delete all crm_notes'),
    ),  
  );
  
  //Generate permissions per crm_note 
  foreach (crm_note_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name crm_note" => array(
        'title' => t('%type_name: Edit any crm_note', array('%type_name' => $type->label)),
      ),
      "view any $type_name crm_note" => array(
        'title' => t('%type_name: View any crm_note', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a crm_note.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $crm_note
 *   Optionally a crm_note or a crm_note type to check access for. If nothing is
 *   given, access for all crm_notes is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function crm_note_access($op, $crm_note = NULL, $account = NULL) {
  if (user_access('administer crm_notes', $account)) {
    return TRUE;
  }
  if (isset($crm_note) && $type_name = $crm_note->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name crm_note", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function crm_note_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer crm_note types', $account);
}


/**
 * Gets an array of all crm_note types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return crm_noteType[]
 *   Depending whether $type isset, an array of crm_note types or a single one.
 */
function crm_note_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our crm_note entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('crm_note_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a crm_note type by string.
 *
 * @param $type
 *   The machine-readable name of a crm_note type to load.
 * @return
 *   A crm_note type array or FALSE if $type does not exist.
 */
function crm_note_type_load($type) {
  return crm_note_get_types($type);
}


/**
 * Fetch a crm_note object. Make sure that the wildcard you choose 
 * in the crm_note entity definition fits the function name here.
 *
 * @param $crm_note_id
 *   Integer specifying the crm_note id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $crm_note object or FALSE if it cannot be loaded.
 *
 * @see crm_note_load_multiple()
 */
function crm_note_load($crm_note_id, $reset = FALSE) {
  $crm_notes = crm_note_load_multiple(array($crm_note_id), array(), $reset);
  return reset($crm_notes);
}


/**
 * Load multiple crm_notes based on certain conditions.
 *
 * @param $crm_note_ids
 *   An array of crm_note IDs.
 * @param $conditions
 *   An array of conditions to match against the {crm_note} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of crm_note objects, indexed by crm_note_id.
 *
 * @see entity_load()
 * @see crm_note_load()
 */
function crm_note_load_multiple($crm_note_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('crm_note', $crm_note_ids, $conditions, $reset);
}


/**
 * Deletes a crm_note.
 */
function crm_note_delete(crm_note $crm_note) {
  $crm_note->delete();
}


/**
 * Delete multiple crm_notes.
 *
 * @param $crm_note_ids
 *   An array of crm_note IDs.
 */
function crm_note_delete_multiple(array $crm_note_ids) {
  entity_get_controller('crm_note')->delete($crm_note_ids);
}


/**
 * Create a crm_note object.
 */
function crm_note_create($values = array()) {
  return entity_get_controller('crm_note')->create($values);
}


/**
 * Saves a crm_note to the database.
 *
 * @param $crm_note
 *   The crm_note object.
 */
function crm_note_save(crm_note $crm_note) {
  return $crm_note->save();
}


/**
 * Saves a crm_note type to the db.
 */
function crm_note_type_save(crm_noteType $type) {
  $type->save();
}


/**
 * Deletes a crm_note type from the db.
 */
function crm_note_type_delete(crm_noteType $type) {
  $type->delete();
}


/**
 * URI callback for crm_notes
 */
function crm_note_uri(crm_note $crm_note){
  return array(
    'path' => 'crm_note/' . $crm_note->crm_note_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function crm_note_page_title(crm_note $crm_note){
  return $crm_note->name;
}


/**
 * Sets up content to show an individual crm_note
 * @todo - get rid of drupal_set_title();
 */
function crm_note_page_view($crm_note, $view_mode = 'full') {    
  $controller = entity_get_controller('crm_note');  
  $content = $controller->view(array($crm_note->crm_note_id => $crm_note));
  drupal_set_title($crm_note->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function crm_note_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_note') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function crm_note_theme() {
  return array(
    'crm_note_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'crm_note.admin.inc',
    ),
    'crm_note' => array(
      'render element' => 'elements',
      'template' => 'crm_note',
    ),
   'crm_note_sample_data' => array(
      'variables' => array('crm_note_sample_data', 'crm_note' => NULL),
      'template' => 'crm_note-sample-data',
    ),


  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function crm_note_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/crm_notes/add' on 'admin/structure/crm_notes'.
  if ($root_path == 'admin/content/crm_notes') {
    $item = menu_get_item('admin/content/crm_notes/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for crm_note entities
 */
class crm_note extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'crm_note');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'crm_note/' . $this->crm_note_id);
  }
  
  
}


/**
 * The class used for crm_note type entities
 */
class crm_noteType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'crm_note_type');
  }
  
}


/**
 * The Controller for crm_note entities
 */
class crm_noteController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a crm_note - we first set up the values that are specific
   * to our crm_note schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the crm_note.
   *
   * @return
   *   A crm_note object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our crm_note
    $values += array( 
      'crm_note_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
    );
    
    $crm_note = parent::create($values);
    return $crm_note;
  }
  
  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    $content['crm_note_sample_data'] =  array(
      '#markup' => theme('crm_note_sample_data', array('crm_note_sample_data' => check_plain($entity->data['sample_data']), 'crm_note' => $entity)),
    );

    return $content;
  }
  
}


/**
 * The Controller for crm_note entities
 */
class crm_noteTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a crm_note type - we first set up the values that are specific
   * to our crm_note type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the crm_note.
   *
   * @return
   *   A crm_note type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our crm_note
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $crm_note_type = parent::create($values);
    return $crm_note_type;
  }

}